services:
  postgres:
    image: postgres
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5435:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: